"""
Health Insurance Claims - generated agent graph.

Generated by compiler/langgraph_gen.py from the stage-1 digest and the stage-2
topology. Regenerate rather than editing by hand; replace the tool stubs and
run_operation with real implementations.

Topology rationale:
  Four agents, not nineteen. The byActor grouping and the bySystem grouping agree on three clean seams: the claimant-facing steps touch only ClaimDB, NotificationSvc and DocumentStore; document checking is the sole consumer of OCRSvc and is machine-driven; appeals sit behind a different trust boundary and must not be decided by the adjuster who made the original call. Assessment stays as one agent because its six operations share the Claim lifecycle and the AssessmentSvc tool, and splitting review from scoring would hand two agents the same state. The four System operations are deterministic - a gateway result and a window expiry - so they are functions with no model in the loop. ClaimDB appears in 12 of 19 operations, which is evidence against splitting further, not for it. An orchestrator is enabled because four agents must hand work back and forth across the claim lifecycle.
"""
from __future__ import annotations

from typing import Any, Literal, TypedDict

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph


class DomainState(TypedDict, total=False):
    """Shared state. `decisions` drives routers until real logic replaces them."""
    entity_id: str
    status: str
    history: list[dict[str, Any]]
    decisions: dict[str, str]
    data: dict[str, Any]


# ---------------------------------------------------------------- tools
# One stub per system named in the domain. Wire these to real clients.

def assessment_svc(action: str, **kwargs: Any) -> Any:
    """AssessmentSvc. Used by: CompleteAssessment, OverturnRejection, ReviewAppeal, StartAssessment, StartReview."""
    raise NotImplementedError("wire AssessmentSvc to a real client")

def claim_d_b(action: str, **kwargs: Any) -> Any:
    """ClaimDB. Used by: AcceptSettlement, ApproveClaim, CloseApproved, CloseRejected, DeclineSettlement, OverturnRejection, RejectClaim, ResubmitInfo, ReviewAppeal, StartReview, SubmitClaim, UpholdRejection."""
    raise NotImplementedError("wire ClaimDB to a real client")

def document_store(action: str, **kwargs: Any) -> Any:
    """DocumentStore. Used by: FlagInvalidDocument, ResubmitInfo, VerifyDocument."""
    raise NotImplementedError("wire DocumentStore to a real client")

def fraud_svc(action: str, **kwargs: Any) -> Any:
    """FraudSvc. Used by: ApproveClaim."""
    raise NotImplementedError("wire FraudSvc to a real client")

def ledger_svc(action: str, **kwargs: Any) -> Any:
    """LedgerSvc. Used by: ExecutePayment."""
    raise NotImplementedError("wire LedgerSvc to a real client")

def notification_svc(action: str, **kwargs: Any) -> Any:
    """NotificationSvc. Used by: AcceptSettlement, DeclineSettlement, RejectClaim, RequestMoreInfo, SubmitClaim, UpholdRejection."""
    raise NotImplementedError("wire NotificationSvc to a real client")

def o_c_r_svc(action: str, **kwargs: Any) -> Any:
    """OCRSvc. Used by: FlagInvalidDocument, VerifyDocument."""
    raise NotImplementedError("wire OCRSvc to a real client")

def payment_gateway(action: str, **kwargs: Any) -> Any:
    """PaymentGateway. Used by: ExecutePayment, FailPayment."""
    raise NotImplementedError("wire PaymentGateway to a real client")

def pricing_svc(action: str, **kwargs: Any) -> Any:
    """PricingSvc. Used by: CompleteAssessment."""
    raise NotImplementedError("wire PricingSvc to a real client")


TOOLS = {'AssessmentSvc': assessment_svc, 'ClaimDB': claim_d_b, 'DocumentStore': document_store, 'FraudSvc': fraud_svc, 'LedgerSvc': ledger_svc, 'NotificationSvc': notification_svc, 'OCRSvc': o_c_r_svc, 'PaymentGateway': payment_gateway, 'PricingSvc': pricing_svc}

# ---------------------------------------------------------------- agents
AGENT_PROMPTS: dict[str, str] = {
    'intake': """You handle claimant-facing steps of a health insurance claim. Collect what is needed, confirm the policy is active on the incident date, and never promise an outcome. When the claimant responds to a settlement offer, record the response exactly as given.""",
    'documents': """You verify documents attached to a claim. Check readability, that the checksum is unique for the claim, and that the document type matches what was requested. Flag anything altered, duplicated or unreadable rather than guessing.""",
    'assessment': """You assess health insurance claims. Review the evidence and the policy terms, record findings and a covered amount, and decide whether to approve, reject or request more information. State the policy clause behind any rejection. High-value and fraud-flagged claims require human approval before you proceed.""",
    'appeals': """You reconsider rejected claims. Weigh only new material evidence against the original rejection reason. You must not simply restate the first decision; if the new evidence is material, overturn it. Every appeal outcome requires human sign-off.""",
}

AGENT_TOOLS: dict[str, list[str]] = {
    'intake': ['ClaimDB', 'NotificationSvc', 'DocumentStore'],
    'documents': ['DocumentStore', 'OCRSvc'],
    'assessment': ['ClaimDB', 'AssessmentSvc', 'FraudSvc', 'NotificationSvc', 'PricingSvc'],
    'appeals': ['ClaimDB', 'AssessmentSvc', 'NotificationSvc'],
    'payments': ['PaymentGateway', 'LedgerSvc'],
    'closure': ['ClaimDB'],
}


def run_operation(state: DomainState, *, op: str, owner: str, kind: str,
                  to_state: str, tools: list[str]) -> dict:
    """Default effect of any operation: record it and advance the state.

    Replace this with real work. For an agent node, call the model with
    AGENT_PROMPTS[owner] and the tools listed. For a function node, call the
    system directly - no model involved.
    """
    return {
        "status": to_state,
        "history": [*state.get("history", []),
                    {"op": op, "owner": owner, "kind": kind, "tools": tools}],
    }


# ---------------------------------------------------------------- nodes

def submit_claim(state: DomainState) -> dict:
    """SubmitClaim: Claim Draft -> Submitted. agent `intake`, risk=low."""
    return run_operation(state, op='SubmitClaim', owner='intake', kind='agent',
                         to_state='Submitted', tools=['ClaimDB', 'NotificationSvc'])

def start_review(state: DomainState) -> dict:
    """StartReview: Claim Submitted -> UnderReview. agent `assessment`, risk=low."""
    return run_operation(state, op='StartReview', owner='assessment', kind='agent',
                         to_state='UnderReview', tools=['ClaimDB', 'AssessmentSvc'])

def request_more_info(state: DomainState) -> dict:
    """RequestMoreInfo: Claim UnderReview -> PendingInfo. agent `assessment`, risk=low."""
    return run_operation(state, op='RequestMoreInfo', owner='assessment', kind='agent',
                         to_state='PendingInfo', tools=['NotificationSvc'])

def resubmit_info(state: DomainState) -> dict:
    """ResubmitInfo: Claim PendingInfo -> UnderReview. agent `intake`, risk=low."""
    return run_operation(state, op='ResubmitInfo', owner='intake', kind='agent',
                         to_state='UnderReview', tools=['ClaimDB', 'DocumentStore'])

def approve_claim(state: DomainState) -> dict:
    """ApproveClaim: Claim UnderReview -> Approved. agent `assessment`, risk=high. [human approval required]"""
    return run_operation(state, op='ApproveClaim', owner='assessment', kind='agent',
                         to_state='Approved', tools=['ClaimDB', 'FraudSvc'])

def reject_claim(state: DomainState) -> dict:
    """RejectClaim: Claim UnderReview -> Rejected. agent `assessment`, risk=high. [human approval required]"""
    return run_operation(state, op='RejectClaim', owner='assessment', kind='agent',
                         to_state='Rejected', tools=['ClaimDB', 'NotificationSvc'])

def close_approved(state: DomainState) -> dict:
    """CloseApproved: Claim Approved -> Closed. function `closure`, risk=low."""
    return run_operation(state, op='CloseApproved', owner='closure', kind='function',
                         to_state='Closed', tools=['ClaimDB'])

def close_rejected(state: DomainState) -> dict:
    """CloseRejected: Claim Rejected -> Closed. function `closure`, risk=medium."""
    return run_operation(state, op='CloseRejected', owner='closure', kind='function',
                         to_state='Closed', tools=['ClaimDB'])

def verify_document(state: DomainState) -> dict:
    """VerifyDocument: Document Uploaded -> Verified. agent `documents`, risk=low."""
    return run_operation(state, op='VerifyDocument', owner='documents', kind='agent',
                         to_state='Verified', tools=['DocumentStore', 'OCRSvc'])

def flag_invalid_document(state: DomainState) -> dict:
    """FlagInvalidDocument: Document Uploaded -> Invalid. agent `documents`, risk=medium."""
    return run_operation(state, op='FlagInvalidDocument', owner='documents', kind='agent',
                         to_state='Invalid', tools=['DocumentStore', 'OCRSvc'])

def start_assessment(state: DomainState) -> dict:
    """StartAssessment: Assessment Pending -> InProgress. agent `assessment`, risk=low."""
    return run_operation(state, op='StartAssessment', owner='assessment', kind='agent',
                         to_state='InProgress', tools=['AssessmentSvc'])

def complete_assessment(state: DomainState) -> dict:
    """CompleteAssessment: Assessment InProgress -> Completed. agent `assessment`, risk=medium. [human approval required]"""
    return run_operation(state, op='CompleteAssessment', owner='assessment', kind='agent',
                         to_state='Completed', tools=['AssessmentSvc', 'PricingSvc'])

def accept_settlement(state: DomainState) -> dict:
    """AcceptSettlement: Settlement Proposed -> Accepted. agent `intake`, risk=low."""
    return run_operation(state, op='AcceptSettlement', owner='intake', kind='agent',
                         to_state='Accepted', tools=['ClaimDB', 'NotificationSvc'])

def decline_settlement(state: DomainState) -> dict:
    """DeclineSettlement: Settlement Proposed -> Declined. agent `intake`, risk=medium."""
    return run_operation(state, op='DeclineSettlement', owner='intake', kind='agent',
                         to_state='Declined', tools=['ClaimDB', 'NotificationSvc'])

def execute_payment(state: DomainState) -> dict:
    """ExecutePayment: Payment Scheduled -> Paid. function `payments`, risk=high. [human approval required]"""
    return run_operation(state, op='ExecutePayment', owner='payments', kind='function',
                         to_state='Paid', tools=['PaymentGateway', 'LedgerSvc'])

def fail_payment(state: DomainState) -> dict:
    """FailPayment: Payment Scheduled -> Failed. function `payments`, risk=high."""
    return run_operation(state, op='FailPayment', owner='payments', kind='function',
                         to_state='Failed', tools=['PaymentGateway'])

def review_appeal(state: DomainState) -> dict:
    """ReviewAppeal: Appeal Filed -> UnderAppealReview. agent `appeals`, risk=medium."""
    return run_operation(state, op='ReviewAppeal', owner='appeals', kind='agent',
                         to_state='UnderAppealReview', tools=['ClaimDB', 'AssessmentSvc'])

def uphold_rejection(state: DomainState) -> dict:
    """UpholdRejection: Appeal UnderAppealReview -> Upheld. agent `appeals`, risk=high. [human approval required]"""
    return run_operation(state, op='UpholdRejection', owner='appeals', kind='agent',
                         to_state='Upheld', tools=['ClaimDB', 'NotificationSvc'])

def overturn_rejection(state: DomainState) -> dict:
    """OverturnRejection: Appeal UnderAppealReview -> Overturned. agent `appeals`, risk=high. [human approval required]"""
    return run_operation(state, op='OverturnRejection', owner='appeals', kind='agent',
                         to_state='Overturned', tools=['ClaimDB', 'AssessmentSvc'])


# ---------------------------------------------------------------- routers

def route_claim_under_review(state: DomainState) -> Literal['request_more_info', 'approve_claim', 'reject_claim']:
    """Approve when the assessment is Completed and the fraud score is below threshold. Reject when a policy exclusion or breach is identified. Otherwise, when a required document is missing or Invalid, request more information.

    Decided by: assessment

    Implement the rule above. Until then this reads state["decisions"], which
    lets you drive the graph in tests. It deliberately raises rather than
    defaulting to a branch: several of these decision points sit on a cycle,
    and an arbitrary default loops forever instead of failing.
    """
    choice = state.get("decisions", {}).get('ClaimUnderReview')
    if choice is None:
        raise NotImplementedError(
            "ClaimUnderReview: no decision recorded. Implement route_claim_under_review, or set "
            "state['decisions']['ClaimUnderReview'] to one of ['request_more_info', 'approve_claim', 'reject_claim']")
    return choice

def route_document_uploaded(state: DomainState) -> Literal['verify_document', 'flag_invalid_document']:
    """Verify when the file is readable and its checksum is unique for the claim. Flag invalid when it is unreadable, duplicated or shows signs of alteration.

    Decided by: documents

    Implement the rule above. Until then this reads state["decisions"], which
    lets you drive the graph in tests. It deliberately raises rather than
    defaulting to a branch: several of these decision points sit on a cycle,
    and an arbitrary default loops forever instead of failing.
    """
    choice = state.get("decisions", {}).get('DocumentUploaded')
    if choice is None:
        raise NotImplementedError(
            "DocumentUploaded: no decision recorded. Implement route_document_uploaded, or set "
            "state['decisions']['DocumentUploaded'] to one of ['verify_document', 'flag_invalid_document']")
    return choice

def route_settlement_proposed(state: DomainState) -> Literal['accept_settlement', 'decline_settlement']:
    """Accept or decline strictly as the claimant responded, provided the offer has not expired. Never infer acceptance from silence.

    Decided by: intake

    Implement the rule above. Until then this reads state["decisions"], which
    lets you drive the graph in tests. It deliberately raises rather than
    defaulting to a branch: several of these decision points sit on a cycle,
    and an arbitrary default loops forever instead of failing.
    """
    choice = state.get("decisions", {}).get('SettlementProposed')
    if choice is None:
        raise NotImplementedError(
            "SettlementProposed: no decision recorded. Implement route_settlement_proposed, or set "
            "state['decisions']['SettlementProposed'] to one of ['accept_settlement', 'decline_settlement']")
    return choice

def route_payment_scheduled(state: DomainState) -> Literal['execute_payment', 'fail_payment']:
    """Paid when the gateway confirms transfer and a ledger entry is written. Failed when the gateway rejects the transfer or bank details do not verify.

    Decided by: payments

    Implement the rule above. Until then this reads state["decisions"], which
    lets you drive the graph in tests. It deliberately raises rather than
    defaulting to a branch: several of these decision points sit on a cycle,
    and an arbitrary default loops forever instead of failing.
    """
    choice = state.get("decisions", {}).get('PaymentScheduled')
    if choice is None:
        raise NotImplementedError(
            "PaymentScheduled: no decision recorded. Implement route_payment_scheduled, or set "
            "state['decisions']['PaymentScheduled'] to one of ['execute_payment', 'fail_payment']")
    return choice

def route_appeal_under_appeal_review(state: DomainState) -> Literal['uphold_rejection', 'overturn_rejection']:
    """Overturn when new material evidence contradicts the original rejection reason. Uphold when no new material evidence is presented.

    Decided by: appeals

    Implement the rule above. Until then this reads state["decisions"], which
    lets you drive the graph in tests. It deliberately raises rather than
    defaulting to a branch: several of these decision points sit on a cycle,
    and an arbitrary default loops forever instead of failing.
    """
    choice = state.get("decisions", {}).get('AppealUnderAppealReview')
    if choice is None:
        raise NotImplementedError(
            "AppealUnderAppealReview: no decision recorded. Implement route_appeal_under_appeal_review, or set "
            "state['decisions']['AppealUnderAppealReview'] to one of ['uphold_rejection', 'overturn_rejection']")
    return choice


# ---------------------------------------------------------------- graphs

def build_claim_graph(checkpointer: Any | None = None):
    """Claim lifecycle: 8 operations, initial='Draft'."""
    g = StateGraph(DomainState)
    g.add_node('submit_claim', submit_claim)
    g.add_node('start_review', start_review)
    g.add_node('request_more_info', request_more_info)
    g.add_node('resubmit_info', resubmit_info)
    g.add_node('approve_claim', approve_claim)
    g.add_node('reject_claim', reject_claim)
    g.add_node('close_approved', close_approved)
    g.add_node('close_rejected', close_rejected)
    g.add_edge(START, 'submit_claim')
    g.add_edge('submit_claim', 'start_review')
    g.add_conditional_edges('start_review', route_claim_under_review, {'request_more_info': 'request_more_info', 'approve_claim': 'approve_claim', 'reject_claim': 'reject_claim'})
    g.add_edge('request_more_info', 'resubmit_info')
    g.add_conditional_edges('resubmit_info', route_claim_under_review, {'request_more_info': 'request_more_info', 'approve_claim': 'approve_claim', 'reject_claim': 'reject_claim'})
    g.add_edge('approve_claim', 'close_approved')
    g.add_edge('reject_claim', 'close_rejected')
    g.add_edge('close_approved', END)
    g.add_edge('close_rejected', END)
    return g.compile(checkpointer=checkpointer or MemorySaver(),
                     interrupt_before=['approve_claim', 'reject_claim'])

def build_document_graph(checkpointer: Any | None = None):
    """Document lifecycle: 2 operations, initial='Uploaded'."""
    g = StateGraph(DomainState)
    g.add_node('verify_document', verify_document)
    g.add_node('flag_invalid_document', flag_invalid_document)
    g.add_conditional_edges(START, route_document_uploaded, {'verify_document': 'verify_document', 'flag_invalid_document': 'flag_invalid_document'})
    g.add_edge('verify_document', END)
    g.add_edge('flag_invalid_document', END)
    return g.compile(checkpointer=checkpointer or MemorySaver())

def build_assessment_graph(checkpointer: Any | None = None):
    """Assessment lifecycle: 2 operations, initial='Pending'."""
    g = StateGraph(DomainState)
    g.add_node('start_assessment', start_assessment)
    g.add_node('complete_assessment', complete_assessment)
    g.add_edge(START, 'start_assessment')
    g.add_edge('start_assessment', 'complete_assessment')
    g.add_edge('complete_assessment', END)
    return g.compile(checkpointer=checkpointer or MemorySaver(),
                     interrupt_before=['complete_assessment'])

def build_settlement_graph(checkpointer: Any | None = None):
    """Settlement lifecycle: 2 operations, initial='Proposed'."""
    g = StateGraph(DomainState)
    g.add_node('accept_settlement', accept_settlement)
    g.add_node('decline_settlement', decline_settlement)
    g.add_conditional_edges(START, route_settlement_proposed, {'accept_settlement': 'accept_settlement', 'decline_settlement': 'decline_settlement'})
    g.add_edge('accept_settlement', END)
    g.add_edge('decline_settlement', END)
    return g.compile(checkpointer=checkpointer or MemorySaver())

def build_payment_graph(checkpointer: Any | None = None):
    """Payment lifecycle: 2 operations, initial='Scheduled'."""
    g = StateGraph(DomainState)
    g.add_node('execute_payment', execute_payment)
    g.add_node('fail_payment', fail_payment)
    g.add_conditional_edges(START, route_payment_scheduled, {'execute_payment': 'execute_payment', 'fail_payment': 'fail_payment'})
    g.add_edge('execute_payment', END)
    g.add_edge('fail_payment', END)
    return g.compile(checkpointer=checkpointer or MemorySaver(),
                     interrupt_before=['execute_payment'])

def build_appeal_graph(checkpointer: Any | None = None):
    """Appeal lifecycle: 3 operations, initial='Filed'."""
    g = StateGraph(DomainState)
    g.add_node('review_appeal', review_appeal)
    g.add_node('uphold_rejection', uphold_rejection)
    g.add_node('overturn_rejection', overturn_rejection)
    g.add_edge(START, 'review_appeal')
    g.add_conditional_edges('review_appeal', route_appeal_under_appeal_review, {'uphold_rejection': 'uphold_rejection', 'overturn_rejection': 'overturn_rejection'})
    g.add_edge('uphold_rejection', END)
    g.add_edge('overturn_rejection', END)
    return g.compile(checkpointer=checkpointer or MemorySaver(),
                     interrupt_before=['overturn_rejection', 'uphold_rejection'])


GRAPHS = {'Claim': build_claim_graph, 'Document': build_document_graph, 'Assessment': build_assessment_graph, 'Settlement': build_settlement_graph, 'Payment': build_payment_graph, 'Appeal': build_appeal_graph}


def build_graph(checkpointer: Any | None = None):
    """Primary lifecycle: Claim."""
    return build_claim_graph(checkpointer)
